### ISSUE TITLE
无法修改网站的icon

### ISSUE THREAD

**Issue by ZherKing** [stilleshan/ServerStatus#1]
网站的icon无法修改 覆盖根目录的ico也不行
添加<link rel="icon" href="favicon.ico">也不行

**Comment by ZherKing** [comment]
link rel="icon" href="favicon.ico"

**Comment by stilleshan** [comment]
docker启动是否挂载了web

**Comment by ZherKing** [comment]
没挂载web我怎么进网站的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Stille ***@***.***&gt;
发送时间: 2021年8月29日 19:10
收件人: stilleshan/ServerStatus ***@***.***&gt;
抄送: zhenjing666 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[stilleshan/ServerStatus] 无法修改网站的icon (#1)





 
docker启动是否挂载了web
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stilleshan** [comment]
我测试更换 favicon.ico 没问题
