### ISSUE TITLE
这个系列的探针 最大的问题就是没有dark

### ISSUE THREAD

**Issue by ihuanx** [stilleshan/ServerStatus#3]
RT

**Comment by stilleshan** [comment]
主题也是hostloc拿的,不会写前端.

**Comment by madlaxcb** [comment]
发现国旗无法显示，全部404.。。

**Comment by stilleshan** [comment]
我这没遇到过这问题
看下config里 "location": "HK", 是不是大写.

**Comment by madlaxcb** [comment]
> 我这没遇到过这问题 看下config里 "location": "HK", 是不是大写.

嗯，找到原因了
